# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Build and Test AIDE Database"
  shell: /usr/sbin/aide --init
  args:
    executable: /bin/bash
  tags:
    @ANSIBLE_TAGS@
