# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Build and Test AIDE Database"
  shell: /usr/sbin/aide --init
  tags:
    @ANSIBLE_TAGS@

- name: Stage AIDE Database"
  shell: cp /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
  tags:
    @ANSIBLE_TAGS@
