# platform = multi_platform_rhel, multi_platform_fedora
# reboot = false
# strategy = unknown
# complexity = low
# disruption = medium
- name: "Enable GNOME3 Screensaver Idle Activation"
  ini_file:
    dest: "/etc/dconf/db/local/d/00-security-settings"
    section: "org/gnome/desktop/screensaver"
    option: idle_activation_enabled
    value: true
    create: yes
  tags:
    @ANSIBLE_TAGS@
