# platform = multi_platform_rhel
# reboot = false
# strategy = restrict
# complexity = medium
# disruption = medium

- name: Set /etc/gshadow permissions
  file:
    path: /etc/gshadow
    mode: 0000
  tags:
    @ANSIBLE_TAGS@

