# platform = multi_platform_rhel
# reboot = false
# strategy = restrict
# complexity = medium
# disruption = medium

- name: Set /etc/group permissions
  file:
    path: /etc/group
    mode: 0644
  tags:
    @ANSIBLE_TAGS@

