# platform = multi_platform_rhel,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = medium
# disruption = medium

- name: Set /etc/passwd user ownership to root
  file:
    path: /etc/passwd
    owner: root
  tags:
    @ANSIBLE_TAGS@

