# platform = multi_platform_rhel
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: Find SSH Keys
  find:
    paths: "/etc/ssh/"
    patterns: "*_key"
  register: find_ssh
  tags:
    @ANSIBLE_TAGS@

- name: Verify Permissions on SSH Server Public *_key Key Files
  file:
    dest: "{{ item.path }}"
    mode: 0644
  with_items: "{{ find_ssh.files }}"
  tags:
    @ANSIBLE_TAGS@
