# platform = multi_platform_rhel, multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = medium
# disruption = medium

- name: Set /etc/passwd permissions
  file:
    path: /etc/passwd
    mode: 0644
  tags:
    @ANSIBLE_TAGS@

