# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Direct root Logins Not Allowed"
  lineinfile:
    dest: /etc/securetty
    regexp: '^vc'
    state: absent
  lineinfile:
    dest: /etc/securetty
    regexp: 'ttyS[0-9]'
    state: absent
  tags:
    @ANSIBLE_TAGS@
