# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "$CCENUM: Set SSH Idle Timeout Interval"
  lineinfile:
    create=yes
    dest="/etc/ssh/sshd_config"
    regexp="^ClientAliveInterval"
    line="ClientAliveInterval (ansible-populate sshd_idle_timeout_value)"

