# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Disable Compression or Set Compression to delayed"
  lineinfile:
    create=yes
    dest="/etc/ssh/sshd_config"
    regexp="^Compression"
    line="Compression delayed"
    validate: sshd -t -f %s
  tags:
    @ANSIBLE_TAGS@
