# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "SSHD: Do not permit user environment"
  lineinfile:
    create=yes
    dest="/etc/ssh/sshd_config"
    regexp="^PermitUserEnvironment"
    line="PermitUserEnvironment no"

